[project]
name = "diffae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning>=2.5.5",
    "lmdb>=1.7.3",
    "lpips>=0.1.4",
    "pandas>=2.3.3",
    "pytorch-fid>=0.3.0",
    "tensorboard>=2.20.0",
]
